# 🏗️ Architecture — Barbershop PHP MVC

> Technical documentation of the MVC structure, request lifecycle, database design, and email flow for AppSalon.

---

## Table of Contents

- [Architectural Pattern](#architectural-pattern)
- [Directory Map](#directory-map)
- [Request Lifecycle](#request-lifecycle)
- [Layer Details](#layer-details)
  - [Entry Point & Router](#1-entry-point--router)
  - [Controllers](#2-controllers)
  - [Models](#3-models)
  - [Views](#4-views)
  - [Configuration & Includes](#5-configuration--includes)
  - [Frontend Pipeline](#6-frontend-pipeline)
- [Database Architecture](#database-architecture)
- [Email Architecture](#email-architecture-phpmailer)
- [Security Model](#security-model)
- [Deployment Notes](#deployment-notes)

---

## Architectural Pattern

The application implements a classic **Model-View-Controller (MVC)** pattern in pure PHP, without a third-party framework. A single entry point (`public/index.php`) receives all HTTP requests, resolves the route, and dispatches to the appropriate controller.

| Layer | Location | Responsibility |
|-------|----------|----------------|
| **Router** | `public/index.php` + `includes/router.php` | Parse URI, map to controller/action |
| **Controller** | `controllers/` | Receive request, call model, select view |
| **Model** | `models/` | SQL queries, PDO, business rules |
| **View** | `views/` | HTML templates with PHP partials |
| **Config** | `includes/` | DB connection, `.env`, helpers, auth middleware |

---

## Directory Map

```
BarberShop_App_MVC/
├── classes/
│   └── Email.php                   # Sends emails (confirmation, password reset) via PHPMailer
│
├── controllers/
│   ├── AuthController.php          # Register, confirm account, login, logout, password recovery
│   ├── AppointmentController.php   # Book, list, cancel appointments; admin appointment view
│   ├── ServiceController.php       # Admin CRUD for services
│   └── AdminController.php         # Admin dashboard, date filtering, access guard
│
├── models/
│   ├── User.php                    # findByEmail, create, confirm, updatePassword
│   ├── Service.php                 # findAll, findById, create, update, delete
│   ├── Appointment.php             # create, findByUser, findByDate
│   └── AppointmentService.php      # Pivot logic: inserts/deletes appointment↔service rows
│
├── views/
│   ├── auth/                       # Login, register, forgot-password, confirm-account templates
│   ├── appointments/                # New booking form, appointment list, admin daily view
│   ├── services/                    # Admin service management templates
│   └── partials/                    # Shared header, footer, nav fragments
│
├── includes/
│   ├── database.php                 # PDO connection singleton
│   ├── router.php                   # Resolves request URI → controller/action
│   ├── helpers.php                  # redirect(), sanitize(), debug(), etc.
│   └── auth.php                     # Session middleware, role/access enforcement
│
├── public/
│   ├── index.php                    # Sole entry point (front controller)
│   └── build/                       # Compiled CSS/JS output (generated by Gulp)
│
├── src/
│   ├── js/                          # Front-end JS source (e.g. app.js, searcher.js)
│   └── scss/
│       ├── base/                     # Resets, variables, mixins, typography
│       ├── components/               # Reusable UI pieces (buttons, forms, alerts...)
│       └── layout/                   # Page-level layout styles
│
├── services/
│   ├── create.php                   # Admin: new service form
│   ├── form.php                     # Shared service form partial
│   ├── index.php                    # Admin: list of services
│   └── update.php                   # Admin: edit service
│
├── templates/
│   ├── alerts.php                   # Flash message partial
│   ├── bar.php                      # Navbar partial
│   └── layout.php                   # Main HTML layout wrapper
│
├── tests/
│   └── email_test.php               # Test script for the Email class
│
├── README.md
├── Router.php                       # Root-level front controller / URI dispatcher
├── .gitignore
├── gulpfile.js                      # Gulp build tasks (SASS compile, JS bundle)
└── package.json                     # npm dependencies and build scripts
```

---

## Request Lifecycle

```
Browser
  │
  ▼
public/index.php          ← sole entry point (all URLs rewritten here)
  │
  ├─ Load autoloader (vendor/autoload.php)
  ├─ Read includes/.env
  ├─ Establish PDO connection (includes/database.php)
  │
  ▼
includes/router.php       ← parse URI into segments
  │
  ▼
Controller::method()      ← instantiated and called
  │
  ├─ Validate input
  ├─ Call Model(s) → PDO queries → MySQL
  │
  ▼
views/template.php        ← render HTML with data
  │
  ▼
Browser receives response
```

**Step by step:**

1. Browser sends HTTP request to any URL (e.g. `/appointments/new`).
2. Apache/PHP rewrites all traffic to `public/index.php` via `.htaccess`.
3. `index.php` boots the app: autoloader, `.env`, DB connection.
4. Router parses the URI and maps it to a controller class + method.
5. Controller is instantiated; method is called with request params.
6. Controller calls one or more Model methods (PDO queries to MySQL).
7. Controller passes data to a View (PHP template) via `include`.
8. View renders HTML and sends it to the browser.

---

## Layer Details

### 1. Entry Point & Router

- `public/index.php` is the **sole entry point** — all requests flow through here.
- URL parsing splits the path into segments: `/controller/action/param`.
- Router maps segments to controller class names (PascalCase convention).
- If no match, a 404 view is served.

**Apache `.htaccess` (required):**
```apache
Options -Indexes
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?url=$1 [QSA,L]
```

**PHP built-in server:**
```bash
php -S localhost:8000 -t public public/index.php
```

---

### 2. Controllers

| Controller | Responsibilities |
|------------|-----------------|
| `AuthController` | Register, confirm email, login, logout, password recovery |
| `AppointmentController` | New booking, list, cancel, admin daily view |
| `ServiceController` | Admin CRUD for barbershop services |
| `AdminController` | Admin dashboard, date filtering, access guard |

> Controllers are **thin**: they validate input, delegate to models, and choose a view. Business logic lives in models or service helpers.

---

### 3. Models

| Model | Key Operations |
|-------|---------------|
| `User` | `findByEmail`, `create`, `confirm`, `updatePassword`, `isAdmin` |
| `Service` | `findAll`, `findById`, `create`, `update`, `delete` |
| `Appointment` | `create`, `findByUser`, `findByDate` (admin), `addServices` |
| `AppointmentService` | Insert pivot rows, delete by appointment |

- All DB access uses **PDO with prepared statements** (no raw string concatenation).
- Models return arrays or objects — no HTML is generated here.

---

### 4. Views

- PHP templates using `include` for shared partials (header, footer, nav).
- Data is passed via controller variables extracted into the view scope.
- **No business logic in views** — only display conditionals and loops.
- SASS-compiled CSS is referenced from `public/build/`.

---

### 5. Configuration & Includes

| File | Purpose |
|------|---------|
| `.env` | Secrets: DB credentials, SMTP config, `APP_URL` |
| `database.php` | PDO singleton; shared across models |
| `router.php` | URI → controller resolution logic |
| `helpers.php` | Utility functions: `redirect()`, `sanitize()`, `debug()` |
| `auth.php` | Middleware: check session, enforce login, enforce admin |

---

### 6. Frontend Pipeline

```
src/scss/  ──[Gulp SASS]──► public/build/app.css
src/js/    ──[Gulp JS]────► public/build/app.js
```

- **Development:** `npm run dev` — watch mode with hot reload.
- **Production:** `npm run build` — minified output.
- Only the compiled files in `public/build/` are served to the browser.

---

## Database Architecture

### Schema

```
USERS (1) ──< APPOINTMENTS (N) ──< APPTSERVICES (N) >── SERVICES (1)
```

| Table | Primary Key | Description |
|-------|-------------|-------------|
| `users` | `id` INT AI | Clients and administrators |
| `services` | `id` INT AI | Available barbershop services |
| `appointments` | `id` INT AI | Booked appointments (date + time) |
| `apptservices` | `id` INT AI | N:M pivot: appointments ↔ services |

### Key Fields

**`users`**
- `admin TINYINT(1)` — `0` = client, `1` = administrator
- `confirmed TINYINT(1)` — `0` = pending email confirmation
- `token VARCHAR(50)` — used for email confirmation and password recovery

**`apptservices` (N:M Pivot)**
- `appointID FK` → `appointments.id`
- `serviceId FK` → `services.id`

### Booking Data Flow

```
1. Client selects service(s), date, time
2. POST → AppointmentController@store
3. Controller validates no time conflict for that slot
4. INSERT into appointments → get lastInsertId()
5. For each service: INSERT into apptservices (pivot)
6. Redirect to appointments list
```

> ⚠️ **Known gap:** server-side time-slot conflict check is not yet implemented. See [Troubleshooting](TROUBLESHOOTING.md#double-booking--same-time-slot-booked-twice).

---

## Email Architecture (PHPMailer)

PHPMailer handles all transactional email via SMTP. An email helper wraps PHPMailer and is called by controllers.

### Email Triggers

| Event | Email Sent |
|-------|-----------|
| User registration | Account confirmation link with token |
| Password recovery | Reset link with one-time token |

### SMTP Configuration

| Property | Source |
|----------|--------|
| Host | `SMTP_HOST` in `.env` |
| Port | `SMTP_PORT` in `.env` (2525 / 587 / 465) |
| Auth | `SMTP_USER` + `SMTP_PASS` from `.env` |
| Environment | Mailtrap (dev) → real SMTP provider (prod) |

```php
$mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS; // port 587
$mail->Port       = 587;
```

---

## Security Model

### Authentication
- Sessions used for login state (`session_start()` in includes).
- Passwords stored as **bcrypt hashes** (`password_hash` / `password_verify`).
- Email confirmation required before first login (`confirmed = 1`).

### Authorization
- `auth.php` middleware checks `$_SESSION` for authenticated user.
- Admin routes additionally check `$_SESSION['admin'] === 1`.
- Unauthenticated users → redirect to `/login`. Non-admins → redirect to `/`.

### Input Validation
- All user input sanitized with `htmlspecialchars` / `filter_var`.
- PDO prepared statements prevent SQL injection.

> ⚠️ **Known gap:** CSRF token validation is not yet implemented on POST forms.

---

## Deployment Notes

- **SMTP:** replace Mailtrap with a real provider (SendGrid, Mailgun, SES) in production.
- **Web server:** configure Apache/Nginx to rewrite all requests to `public/index.php`.
- **Environment:** set `APP_URL` to the production domain in `.env`.
- **Build:** run `composer install --no-dev` and `npm run build` before deploying.
- **Security:** ensure `includes/.env` is in `.gitignore` and never committed.

---

← [Back to README](../README.md)
